{% set build_num = 0 %}
{% set pyston_version = "2.3.5" %}
{% set python_version = "3.8.*" %}

package:
  name: pyston_lite
  version: {{ pyston_version }}
  skip: True  # [not linux]

source:
  path: ../../../

outputs:
  - name: pyston_lite

    build:
      script: cd pyston/pyston_lite; PYSTON_USE_SYS_BINS=1 python setup.py install -v
      detect_binary_files_with_prefix: true

    requirements:
      host:
        - {{ compiler('c') }}
        - python {{ python_version }} *_cpython
        - luajit  # [not aarch64] # unfortunately not available on aarch64, use the debian package instead
        - bolt >=2022.04.11 *_pyston  # [x86]
      run:
        - python {{ python_version }} *_cpython

  - name: pyston_lite_autoload

    build:
      script: cd pyston/pyston_lite/autoload; python setup.py install -v

    requirements:
      host:
        - python {{ python_version }} *_cpython
        - {{ compiler('c') }}
      run:
        - {{ pin_subpackage('pyston_lite', exact=True) }}


    test:
      commands:
        - python -c "import sys; assert 'pyston_lite' in sys.modules"
