{% set build_num = 0 %}
{% set version = "2022.04.11" %}

package:
  name: bolt
  version: {{ version }}

source:
  git_url: https://github.com/llvm/llvm-project
  git_rev: c29a51b3a257908aebc01cd7c4655665db317d66
  git_depth: -1

build:
  number: {{ build_num }}
  string: {{ build_num }}_pyston
  skip: True  # [not x86]

outputs:
  - name: bolt
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - cmake
        - zlib
        - ncurses

      run:
        - zlib
        - ncurses

test:
  commands:
    - llvm-bolt --version
    - perf2bolt --version
    - merge-fdata --version

about:
  home: https://github.com/llvm/llvm-project/
  licence: Apache License v2.0 with LLVM Exceptions
  licence_file: LICENCE.TXT
  summary: BOLT is a post-link optimizer developed to speed up large applications.
